### ISSUE TITLE
Amendment to bot's response to audio recordings

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#10]
After an audio message has been sent, rather than the bot saying ‘thanks for recording’, perhaps its response can be more conducive of another group member responding too (e.g., “Ah, interesting [user that recorded]. What do you think, [other user]?”).

**Comment by lydgate** [comment]
Ah, great idea! So this will apply only in groups presumably. Do you know how many people will be in a group? I guess I'm curious if it's 2, or more? It sounds like more, and it should pick another user at random?

**Comment by Gryphire** [comment]
Yes, indeed, I think your very first instantiation of the response still works fine in solo conversations with Wisperbot. If possible, it might be great to call upon all others (I imagine groups would probably not be larger than 4 for now). So smth like  'What about you _(or equivalent)_, [name1], [name2], and [name3]?'
