### ISSUE TITLE
Have Wisperbot send conversation-restarting reminder 

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#11]
If the conversation seems to die down (e.g., no audio messages have been sent in a while), the bot can perhaps send a message reminding people and stimulating a continuation of the conversation.

**Comment by lydgate** [comment]
This is a great idea, can you give me an idea of how many/when you are thinking? E.g. would it just be a one-off after a week, or would it be more sophisticated than that?

**Comment by Gryphire** [comment]
I think in its simplest useful form it would be great if the reminder works as a sort of timer (re)starting form the moment the most recent voice message comes in, and initiates a reminder message when (e.g.) 24/48/72/variableX hours pass since that last message.

**Comment by lydgate** [comment]
OK, I've gotten somewhere with scheduling the jobs using JobQueue, but I can't seem to cancel them yet. Not sure if this can be done directly from JobQueue, or whether we would need to use the more complex APSCheduler.

It also looks like JobQueue may not persist through reboots of the bot, and that it would require some fairly substantial coding to support that.

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions---JobQueue
https://github.com/python-telegram-bot/ptbcontrib/tree/main/ptbcontrib/ptb_jobstores

**Comment by lydgate** [comment]
OK, I've implemented a version of this; detailed description in the commit message. I suspect the way it works now will be annoying, but it's worth testing.
