### ISSUE TITLE
Finetuning the 'user chose prompt x' logging

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#17]
At the moment the bot's backend logs a 'user chose prompt x' event every time the code checks whether or not a prompt is already saved in the prompt file. It would be great if that behaviour can be finetuned so that it only logs that message when an actual change is made to the prompt (i.e., a new prompt is chose by a user) (or a prompt is chosen for the first time, obviously).

**Comment by lydgate** [comment]
OK, now it checks if the prompt has changed before logging.

Does this look ok for the normal logging format? I will add CSV format if so.

```
2023-09-21 17:49:23,379 - chat-5920741802 - INFO - Bryan chose prompt How do you balance helping people and protecting your own boundaries?
2023-09-21 17:49:23,500 - chat-5920741802 - INFO - Sent response to Bryan
```

**Comment by Gryphire** [comment]
Yes, looks great. Maybe we can add ‘Wisperbot [action]’ to all of the events that Wisperbot is the source of? So ‘Wisperbot sent response to Bryan’ in this particular example. It’s a very minor thing but will reduce noise later down the line.

**Comment by lydgate** [comment]
Great, I will do that as I go through and add support for CSV logging.
