### ISSUE TITLE
Generate separate event logs for different chats

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#2]
Need to figure out how we can save the event logs of separate chats to different files rather than to one file (which is the case now).

**Comment by lydgate** [comment]
Had a quick stab at logging by chat_id, can you see if that works?

**Comment by Gryphire** [comment]
Initiation of logging by /start command works. Our next steps:

- We should try to make sure logging works even though /start may never be called
- Let's include time in logged information (as with the console log), easier to trace back what happened when
- Include chat_type in log file name so it's easier to see if the log pertains to a solo chat or a group chat
- Need to ensure continuity of log over time (i.e., it seems like I may have multiple different logs for one and the same chat stream). When I got the bot back up and running just now a number of extra log files popped up, and I couldn't make out from what conversations those came, some weird username was featured too; 〶 ̅̅ᏕᏗᏒᏗᏖᏂ═─◄█▓▒░✌.(◕‿-)

**Comment by Gryphire** [comment]
Have implemented the log file name change to include chat type and date & time created for better traceability.

**Comment by Gryphire** [comment]
Have now implemented adding the event timestamps to the log file's contents.

**Comment by Gryphire** [comment]
With regards to the file logger continuity issue: it seems that file logging for a specific chat ID ceases (understandably) when for some reason the bot stops running (this could be the case if we manually stop running the bot file or, later, if there's server issues). After restart, logging for the same chat ID **does not resume**. Need to find a way to fix this.

**Comment by lydgate** [comment]
8b99603 should filter out annoying HTTP messages

**Comment by lydgate** [comment]
OK, I've had a go at creating a `setup_dir` function which will create a new directory and warn if a directory already exists. This function now gets called from both `start_command` and `msg` so it should start logging whenever the bot receives *any* text. If this is not sufficient we could also call it from `filters.Update` which triggers on every update the bot receives, but I'm not sure this is a good idea.

I tested running the bot, sending a non-`/start` command, killing the bot, then restarting, and sending another message. It resumed logging.

current format of the log is: `logs/<type>/<user or group name>-<chat id>/chat-<chat id>.log` which is a bit redundant but hopefully fine? Feel free to reconfigure if you want.

Example: `/logs/private/Bryan-5920741802/chat_5920741802.log`

**Comment by lydgate** [comment]
I took it out so that it doesn't start a new log file each time the bot starts. Done a few things...

- separated out directories (feel free to change the locations/formats of course to whatever you prefer)
- filtered out HTTP
- now logging should hopefully resume but this needs to be tested
- Logging should also work without /start but currently it depends on some kind of text message. Lmk if that isn't sufficient, we can easily start logging on receipt of a voicenote too for example

**Comment by Gryphire** [comment]
Current logging state:

- Persistence of chat-specific event logging across bot sessions is intact
- Warning of chat-specific directory existing is being issued in response to every interaction with the bot
- Events are logged double, triple, quadruple etc. as the interactions with the bot progress

**Comment by lydgate** [comment]
OK, I did a basic check within `setup_dir`: it just checks that there are two logging streams, one is to `stderr` and the other is to a file. And I removed the warning, but I added an info line when it first starts logging.
