### ISSUE TITLE
Setting up status variable

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#23]
Making sure we can keep track of where in the flow of the tutorial (and later on, main Wisper experience) the user is, so that we'll be able to respond adequately to their interactions with Wisperbot.

**Comment by lydgate** [comment]
Oops, originally updated #24, but moving the initial development over here, as this should be closed first.

OK, I've switched the attribute from `tutorial_complete` to `status`. Currently there are only two statuses:

1. 'tutorial'
1. 'tutorial_complete'

Will need to think about the later ones.

**Comment by Gryphire** [comment]
Great! 

Here are the values I'd like `status` to take on depending on the user's location in the experience flow:

**WITHIN TUTORIAL PHASE**
- 'tut_started' 
_(set as a result of using the /starttutorial command)_
- 'tut_story1received' 
_(set as a result of /gettutorialstory OR in any case when the first tutorial story has been sent to user)_
- 'tut_story1responded' 
_(set as a result of user having sent in audio to bot while in story1sent status?)_
- 'tut_story2received' 
_(at this point I believe the next story is sent automatically as a result of user submitting audio to previous)_
- 'tut_story2responded' _(idem)_
- 'tut_story3received' _(idem)_
- 'tut_story3responded' _(idem)_
- 'tut_story4received' _(idem)_
- 'tut_story4responded' _(idem)_
- 'tut_completed' _(set as a result of using the /endtutorial command)_

**MAIN PHASE** (this is where it gets tricky but let's start with these, and they're not necessarily listed chronologically)
- 'storyprompt_requested'  (then user has requested a prompt to record their own story about)
- 'story_submitted' (when user has recorded a story based on previously requested prompt)
- 'story_requested' (when user has requested to hear another random user's story)
- 'response_submitted' (when user has submitted 
These values I imagine users will oscillate between during their time using the bot's main phase.

**Comment by lydgate** [comment]
OK, a2ccf76e635131aed42dbb2dcb19c62d10787437 should implement all the tutorial phases above, plus `none` when the chat first starts and also `start_welcomed` after receiving `/start`.
