### ISSUE TITLE
Build in conditional voice note handling based on status variable

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#24]
Handling voice notes according to status, i.e. being able to differentiate between voice notes that are recorded as a story (following a prompt) and voice notes that are recorded as a response to another person's requested story.

**Comment by lydgate** [comment]
OK, I've switched the attribute from `tutorial_complete` to `status`. Currently there are only two statuses:

1. 'tutorial'
1. 'tutorial_complete'

Will need to think about the later ones.

**Comment by lydgate** [comment]
OK, I've had a go at this in the development branch. Basically it modifies the `get_voicenote` function to handle the following statuses:

- `none` (right as chat is initiated)
- `tut_story1received` or `tutstory1responded` (and so on) when the user has received or responded to one of the tutorial stories
- I created placeholder logic for `awaiting_story_response` and `story_response_received` for when we deal with other users' stories.

Let me know if this looks ok?

Thanks,

Bryan
