### ISSUE TITLE
Building out skeleton for main phase using ConversationHandler

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#29]
Now that the foundation has been set for the tutorial phase, we can work on the main phase!

**Comment by lydgate** [comment]
If a user is not defined in the `user_pairs.csv` file (by username), it won't allow them to interact with the bot.

**Comment by lydgate** [comment]
OK, now when a user runs `/start` it will check if they have been defined in the csv file. If not, it will tell them sorry and stop talking. Otherwise, it will tell them the username of whom they are paired with, and start the main sequence.

**Comment by lydgate** [comment]
`user_pairs.csv`:
`bryan_kam,NastasiaGriffioen`

**Comment by lydgate** [comment]
To do:

- [ ] Let them know that the other person the other's status if they haven't finished onboarding on day 2
- [ ] Show on backend how each pair is doing (either as a text file
- [ ] Tell them they are being paired (make it clear they might need to wait), ask for short intro to be recorded after final tutorial story
- [ ] After they've both recorded their voicenotes, send them to each other when the second one comes in

"Thanks for completing the tutorial, you've been paired with Nastasia, here's the introduction she has recorded."

**Comment by lydgate** [comment]
Cleaned up the code a bit, updated openai, reinstated transcription option.

Still need to ask users for intros and send intros to each other.

**Comment by lydgate** [comment]
A few changes on this branch:

- Stop the bot from responding/logging when interacting with an unknown user (#38)
- Figure out why we sometimes get `update` without `update.message`
