### ISSUE TITLE
Set up bot keeping track of days since on-boarding

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#33]
We'll need the bot to know 'what day it is' relative to the on-boarding start date, so that we can send day-specific instructions and reminders.

**Comment by lydgate** [comment]
This should now be working for the first week, at least in a draft form! May still be some bugs. See the attached branch.

**Comment by lydgate** [comment]
OK! Mostly working but had trouble with the apscheduler on Nas' end. I've tried setting job_kwargs with misfire_grace_time set to None, which means it should send it no matter how late.

https://docs.python-telegram-bot.org/en/stable/telegram.ext.jobqueue.html#telegram.ext.JobQueue.job_callback.params.job_queue

job_kwargs (dict) – Arbitrary keyword arguments. Used as arguments for apscheduler.schedulers.base.BaseScheduler.add_job().

https://apscheduler.readthedocs.io/en/3.x/modules/schedulers/ base.html#apscheduler.schedulers.base.BaseScheduler.add_job

misfire_grace_time (int) – seconds after the designated runtime that the job is still allowed to be run (or None to allow the job to run no matter how late it is)
