### ISSUE TITLE
Only send audio files once both parties have submitted

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#35]
It'd be great if we can figure out whether this is possible. My sense is that if I were to still be in the process of completing my end of the task, and I would then already receive the other person's audio, the odds of me getting distracted or influenced by that audio are high. This is something I would like to avoid, so keeping the audio files 'under embargo' as long as not everyone in the dyad has completed their task would probably be preferred.

**Comment by lydgate** [comment]
Looking at this today, so far it seems like it's a bit tricky to wait for a user response and interpret it, at least the way we've currently designed the bot. It looks like we might need to use `ConversationHandler` which tracks the user's conversation through each stage, to know what to do with responses at different points. It's also possible we could get around doing this by using `MessageReactionHandler` in a loop somehow, but it's not obvious how yet. https://docs.python-telegram-bot.org/en/stable/telegram.ext.messagereactionhandler.html

**Comment by lydgate** [comment]
OK, I've spent a few hours looking at this, it would probably be best to rewrite the bot if we're going to use ConversationHandlers. 
https://docs.python-telegram-bot.org/en/stable/telegram.ext.conversationhandler.html#conversationhandler

It would look something like this...

```
conv_handler = ConversationHandler(
    entry_points=[CommandHandler('start', start)],
    states={
        START_WELCOMED: [MessageHandler(filters.TEXT, start_welcomed)],
        TUT_STARTED: [MessageHandler(filters.TEXT, tut_started)],
        TUT_STORY1RECEIVED: [MessageHandler(filters.TEXT, tut_story1received)],
        TUT_STORY2RECEIVED: [MessageHandler(filters.TEXT, tut_story2received)],
        TUT_STORY3RECEIVED: [MessageHandler(filters.TEXT, tut_story3received)],
        TUT_STORY4RECEIVED: [MessageHandler(filters.TEXT, tut_story4received)],
        TUT_STORY1RESPONDED: [MessageHandler(filters.TEXT, tut_story1responded)],
        TUT_STORY2RESPONDED: [MessageHandler(filters.TEXT, tut_story2responded)],
        TUT_STORY3RESPONDED: [MessageHandler(filters.TEXT, tut_story3responded)],
        TUT_STORY4RESPONDED: [MessageHandler(filters.TEXT, tut_story4responded)],
        TUT_COMPLETED: [MessageHandler(filters.TEXT, tut_completed)],
        AWAITING_INTRO: [MessageHandler(filters.TEXT, awaiting_intro)]
    },
    fallbacks=[CommandHandler('cancel', cancel)]
)
```

Benefits: much clearer tracking of where the user is in the process (we can still store status). Much easier to make the bot respond in different ways at different times without doing our own external tracking of state.

Cost: just development time, I think. Adds complexity too, since the bot currently "always" saves voicenotes and logs chats for example, whereas we might wind up in states where we need to be careful about what's going in.

**Comment by lydgate** [comment]
Much of this has been done and refactored in #29, but still some work to be done.

Worth having a look at [this example](https://docs.python-telegram-bot.org/en/stable/examples.conversationbot.html) to see a simple implementation of a conversation using the `ConversationHandler`.

- [Another bot](https://docs.python-telegram-bot.org/en/stable/examples.conversationbot2.html)
- [Nested conversation](https://docs.python-telegram-bot.org/en/stable/examples.nestedconversationbot.html)
- [Persistent bot](https://docs.python-telegram-bot.org/en/stable/examples.persistentconversationbot.html)

**Comment by lydgate** [comment]
OK, several changes. Now the bot will log the paired username, which it gets from the `user_pairs.csv` file. One issue was that it won't know the other user's `chat_id` until that user has run `/start` on the bot.

Now, when the user gets to the introduction stage, it will check whether it knows the paired user's `chat_id` or not. If not, it will wait. If it does, it will exchange the voicenotes.

Currently the way it exchanges voicenotes is just to duplicate all the steps we've run through. Possibly this could be put into a function, if we'll be exchanging lots of voicenotes depending on status.
