### ISSUE TITLE
Final response audio not sent

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#52]
The youth advisors have now run through the entirety of Week 1. All looks good, except that the very final audio (that of the final response that the original storyteller sends as a reaction to the other's active listening response) was not being delivered. Having taken a look at the database, log and code, that's not an error but we simply forgot to add in the audio sending in that section.

I think these line changes fix it (see highlighted areas in attached screenshot) but maybe you can do a sanity check, @lydgate? 

![image](https://github.com/Gryphire/wisperbot/assets/17269537/6bb4bd59-fcfe-422f-9609-24890ca2d090)

**Comment by Gryphire** [comment]
To be clear; I have not pushed this new file to the repo yet, so you won't find these changes in the files here yet (don't wanna break anything ;P).

**Comment by lydgate** [comment]
Hi Nas, yes this looks right to me! I've just made a branch here so feel free to push the changes, then we can test/PR.
