### ISSUE TITLE
Both users in dyad stuck right after recording prompt response

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#61]
Aaaaand we have another curious little issue that popped up. 
I got word that both parties in one dyad received the following message from the bot after having sent in their response to the week 1 prompt, see screenshot. Normally, you would expect them to receive the message about whether or not they want to send in another audio, or if they want to hit /done (and this worked fine in my own dyad, the one that stranded at the final feedback).

![image](https://github.com/user-attachments/assets/2e8107e3-0988-45c1-895f-33d90ba8fe57)

As a result, they seem stuck UNLESS they record another response (after which they get the option to either record one more or hit /done). I have located the message that they got in the echobot.py code (see second screenshot) but unfortunately I'm not sure what to make of the fact that it was triggered. Hoping you can clarify and that we can figure out how to fix this. (: 

<img width="698" alt="image" src="https://github.com/user-attachments/assets/b3cd0178-170c-4827-adb9-2839f7229931">

**Comment by lydgate** [comment]
OK, I think I found this and a related issue, should be fixed in the branch for #60. Please let me know how testing goes :blush:

**Comment by Gryphire** [comment]
Is fixed!
