### ISSUE TITLE
Adjusted /prompt command: shortlist instead of one option

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#9]
Youth advisors have requested that upon calling the /prompt command the bot should provide a short list selection from the database rather than just one option. 

If possible, the bot should also enable users to vote on items in the provided list so that they can decide on which prompt they will be going with in a streamlined manner.

**Comment by lydgate** [comment]
Probably we can do this using a poll.

See these:

- https://towardsdatascience.com/creating-a-telegram-chatbot-quiz-with-python-711a43c0c424
- https://core.telegram.org/bots/api-changelog#april-24-2020

> Yes! The way I envision it, it could be a selection of three prompts from the database file, and they all can vote on the prompt (or maybe prompts, so allowing multiple votes) they would be interested in discussing.
> Not sure if the api functionality allows it, but if the poll could also automatically detect when everybody has voted and which answer won that’d be great, because otherwise I foresee people might linger for quite a while in that space between voting and acting on the outcome.

Would not need cross-chat coordination, and can be stored in json in the `files` directory.

**Comment by lydgate** [comment]
Basic (annoying) counting should be working; still need to figure out how to get the number of people in a group but it should be straightforward. Only question is how to update that number as people are added...

**Comment by lydgate** [comment]
- When running /prompt, it should still show the keyboard, and if they choose Value Tensions then it will present a poll.
- Poll will be sent and users can vote
- If all users vote OR three hours pass, the poll will end, and a random prompt from among those with the highest vote will be selected
- This should work for the authentic relating section as well (different category in `prompts.csv`)
- If nobody votes, a message that the voting has ended with no winner
